# Generated by Django 4.2.5 on 2023-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255)),
                ('second', models.CharField(max_length=255, null=True)),
                ('third', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
